package infra

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

type Mode string

const (
	ModeGlobal Mode = "global"
	ModeLocal  Mode = "local"
)

type CodexConfigMode string

const (
	CodexConfigModePreserve CodexConfigMode = "preserve"
	CodexConfigModeGlobal   CodexConfigMode = "global"
	CodexConfigModeLocal    CodexConfigMode = "local"
)

type Layout struct {
	Mode      Mode
	SourceDir string
	RootDir   string
	AgentsDir string
	ClaudeDir string
	CodexDir  string
	BinDir    string
}

type Options struct {
	Layout                    Layout
	NoSync                    bool
	CodexConfigMode           CodexConfigMode
	PrimarySessionSetup       CodexPrimarySessionSetup
	ClaudePrimarySessionSetup ClaudePrimarySessionSetup
	Stdout                    io.Writer
	projectConfigAtomicWriter projectConfigAtomicWriter
}

type Report struct {
	Layout                   Layout
	AgentsGitFree            bool
	ClaudeLinked             bool
	CodexLinked              bool
	CodexRendered            bool
	CodexProjectRendered     bool
	CodexConfigPresent       bool
	CodexConfigLinked        bool
	CodexConfigGenerated     bool
	CodexConfigShadowsGlobal bool
	CodexConfigEffective     string
	CodexMCPEnabled          []string
	CodexPrimaryConfigValid  bool
	CodexPrimarySession      CodexPrimarySessionPolicy
	ClaudePrimaryConfigValid bool
	ClaudePrimarySession     ClaudePrimarySessionPolicy
	HelpersLinked            bool
	InfraSkillLink           bool
	CanonicalTargets         []DoctorCanonicalTarget
	PiProfileFieldGaps       []ProjectProfileFieldGap
}

type DoctorCanonicalTarget struct {
	Entrypoint       string
	EntrypointSource string
	Name             string
	TargetSource     string
	Vendor           string
	Environment      string
	Model            string
	Reasoning        string
	Profile          string
	ProfileSource    string
	ProfileProvider  string
	Endpoint         string
}

const generatedInstructionsMarker = "<!-- Generated by agents-infra; do not edit directly. -->"
const generatedCodexConfigMarker = "# Generated by agents-infra; do not edit directly."
const projectConfigFileName = "project-config.toml"
const repoSkillName = "relux-agents-infra"
const legacyLiteralSourceDirName = "$AGENTS_INFRA_SOURCE_DIR"

// The Claude entrypoint and project scaffold bodies live with the v1 prepare
// compatibility renderer in legacy_prepare_instructions.go; ordinary setup no
// longer distributes instructions.

func GlobalLayout(sourceDir, homeDir string) (Layout, error) {
	if homeDir == "" {
		return Layout{}, fmt.Errorf("home directory is required")
	}
	homeDir, err := filepath.Abs(homeDir)
	if err != nil {
		return Layout{}, fmt.Errorf("resolve home dir: %w", err)
	}
	return Layout{
		Mode:      ModeGlobal,
		SourceDir: sourceDir,
		RootDir:   homeDir,
		AgentsDir: filepath.Join(homeDir, ".agents"),
		ClaudeDir: filepath.Join(homeDir, ".claude"),
		CodexDir:  filepath.Join(homeDir, ".codex"),
		BinDir:    filepath.Join(homeDir, ".local", "bin"),
	}, nil
}

func LocalLayout(sourceDir, projectDir string) (Layout, error) {
	if projectDir == "" {
		return Layout{}, fmt.Errorf("project directory is required")
	}
	projectDir, err := filepath.Abs(projectDir)
	if err != nil {
		return Layout{}, fmt.Errorf("resolve project dir: %w", err)
	}
	return Layout{
		Mode:      ModeLocal,
		SourceDir: sourceDir,
		RootDir:   projectDir,
		AgentsDir: filepath.Join(projectDir, ".agents"),
		ClaudeDir: filepath.Join(projectDir, ".claude"),
		CodexDir:  filepath.Join(projectDir, ".codex"),
		BinDir:    filepath.Join(projectDir, ".local", "bin"),
	}, nil
}

func Setup(opts Options) error {
	if opts.Layout.Mode == ModeLocal && opts.Layout.SourceDir != "" {
		resolved, err := resolveLocalSetupLayout(opts.Layout)
		if err != nil {
			return err
		}
		opts.Layout = resolved
	}
	if _, err := normalizeCodexConfigMode(opts.CodexConfigMode); err != nil {
		return err
	}
	if opts.Layout.Mode == ModeLocal {
		if err := ValidateCanonicalProjectConfiguration(opts.Layout.RootDir, ""); err != nil {
			return err
		}
	}
	preparedProjectConfig, err := preparePrimarySessionSetup(
		opts.Layout,
		opts.PrimarySessionSetup,
		opts.ClaudePrimarySessionSetup,
		opts.projectConfigAtomicWriter,
	)
	if err != nil {
		return err
	}
	if err := requireLayoutSourceDir(opts.Layout); err != nil {
		return err
	}
	// From here on the destination is being rewritten, so it stops vouching for
	// itself until this run finishes and passes its postconditions.
	if err := invalidateRuntimeReceipt(opts.Layout.AgentsDir); err != nil {
		return err
	}
	if !opts.NoSync {
		if err := syncRepo(opts.Layout); err != nil {
			return err
		}
		logf(opts.Stdout, "Synced source repo into %s", opts.Layout.AgentsDir)
	}
	if err := removeGlobalProjectConfig(opts.Layout, opts.Stdout); err != nil {
		return err
	}
	if err := scrubInstalledGitMetadata(opts.Layout, opts.Stdout); err != nil {
		return err
	}
	if err := scrubGeneratedArtifacts(opts.Layout, opts.Stdout); err != nil {
		return err
	}
	if err := RefreshLinks(opts); err != nil {
		return err
	}
	if err := commitPreparedProjectConfig(preparedProjectConfig, opts.Stdout); err != nil {
		return err
	}
	// Postcondition, not a label: what was installed has to be usable before the
	// run is allowed to mark it so.
	if err := verifyRuntimeArtifacts(opts.Layout); err != nil {
		return err
	}
	return writeRuntimeReceipt(opts.Layout)
}

// resolveLocalSetupLayout is the production setup-local recursion gate. It
// resolves both roots before any destination validation or mutation, then
// refuses a source that is the project or one of its ancestors. Comparing
// directory identities while walking the project ancestry covers symlink and
// case aliases on filesystems whose path spelling is not their identity.
func resolveLocalSetupLayout(layout Layout) (Layout, error) {
	resolvedSource, err := canonicalSetupDirectory(layout.SourceDir, "source")
	if err != nil {
		return Layout{}, err
	}
	resolvedProject, err := canonicalSetupDirectory(layout.RootDir, "project")
	if err != nil {
		return Layout{}, err
	}

	contains, equal, err := directoryContainsByIdentity(resolvedSource, resolvedProject)
	if err != nil {
		return Layout{}, fmt.Errorf("compare resolved setup local paths: %w", err)
	}
	if contains {
		reason := "contains the resolved project directory"
		if equal {
			reason = "is the same directory as the resolved project directory"
		}
		return Layout{}, fmt.Errorf(
			"refusing setup local: resolved source directory %s %s %s; syncing would copy the source into its own project-local destination. Choose an agents-infra source directory outside the project; for config-only changes, combine that external source with --no-sync",
			resolvedSource,
			reason,
			resolvedProject,
		)
	}

	// Resolution is for the safety decision and its diagnostic. Preserve the
	// caller's cleaned absolute layout spelling for installed symlink targets,
	// receipts, and logs; on macOS /var and /private/var are the same identity
	// but are intentionally not interchangeable output bytes.
	return layout, nil
}

func canonicalSetupDirectory(path, label string) (string, error) {
	abs, err := filepath.Abs(path)
	if err != nil {
		return "", fmt.Errorf("resolve %s directory: %w", label, err)
	}
	resolved, err := filepath.EvalSymlinks(filepath.Clean(abs))
	if err != nil {
		return "", fmt.Errorf("resolve %s directory %s: %w", label, abs, err)
	}
	info, err := os.Stat(resolved)
	if err != nil {
		return "", fmt.Errorf("stat resolved %s directory %s: %w", label, resolved, err)
	}
	if !info.IsDir() {
		return "", fmt.Errorf("resolved %s path is not a directory: %s", label, resolved)
	}
	return filepath.Clean(resolved), nil
}

func directoryContainsByIdentity(outer, inner string) (contains bool, equal bool, err error) {
	outerInfo, err := os.Stat(outer)
	if err != nil {
		return false, false, fmt.Errorf("stat source directory %s: %w", outer, err)
	}
	for current := inner; ; current = filepath.Dir(current) {
		currentInfo, statErr := os.Stat(current)
		if statErr != nil {
			return false, false, fmt.Errorf("stat project ancestor %s: %w", current, statErr)
		}
		if os.SameFile(outerInfo, currentInfo) {
			return true, samePath(outer, inner), nil
		}
		parent := filepath.Dir(current)
		if parent == current {
			return false, false, nil
		}
	}
}

// RefreshLinks refreshes only the residual links setup owns: Claude settings,
// Codex config state and rules, helper launchers, and the local CLI wrapper.
// It never distributes instructions, skills, or MCP registries; the v1 prepare
// compatibility renderer owns instruction artifacts for installed runtimes.
func RefreshLinks(opts Options) error {
	if _, err := normalizeCodexConfigMode(opts.CodexConfigMode); err != nil {
		return err
	}
	if err := setupClaudeSettings(opts.Layout, opts.Stdout); err != nil {
		return err
	}
	if err := setupCodex(opts.Layout, opts.CodexConfigMode, opts.Stdout); err != nil {
		return err
	}
	if err := setupHelpers(opts.Layout, opts.Stdout); err != nil {
		return err
	}
	return installCLIWrapper(opts.Layout, opts.Stdout)
}

// Doctor reports residual installation state and project policy. The
// ClaudeLinked, CodexLinked, CodexRendered, CodexProjectRendered, and
// InfraSkillLink fields are legacy observations of native-home state that
// setup no longer manages; they are reported for external consumers, never as
// residual health requirements.
func Doctor(layout Layout) (Report, error) {
	report := Report{
		Layout:                   layout,
		CodexPrimaryConfigValid:  true,
		ClaudePrimaryConfigValid: true,
	}
	if _, err := os.Stat(filepath.Join(layout.AgentsDir, ".git")); err == nil {
		report.AgentsGitFree = false
	} else {
		report.AgentsGitFree = true
	}
	report.ClaudeLinked = isLinkTo(filepath.Join(layout.ClaudeDir, "instructions"), filepath.Join(layout.AgentsDir, ".instructions"))
	report.CodexLinked = isLinkTo(filepath.Join(layout.CodexDir, "AGENTS.md"), filepath.Join(layout.AgentsDir, ".instructions", "AGENTS.md"))
	report.CodexRendered = isRenderedInstructionsFile(filepath.Join(layout.CodexDir, "AGENTS.md"))
	codexConfigPath := filepath.Join(layout.CodexDir, "config.toml")
	report.CodexConfigPresent = pathExists(codexConfigPath)
	report.CodexConfigLinked = isLinkTo(codexConfigPath, filepath.Join(layout.AgentsDir, ".configs", "codex-config.toml"))
	report.CodexConfigGenerated = isGeneratedCodexConfigFile(codexConfigPath)
	report.CodexConfigEffective = "global"
	report.HelpersLinked = isGeneratedAgentsAttachmentsLauncher(filepath.Join(layout.BinDir, agentsAttachmentsWrapperName(runtime.GOOS))) && len(piInfraLauncherFailures(layout)) == 0 && len(canonicalTargetLauncherFailures(layout)) == 0
	report.InfraSkillLink = isLinkTo(
		filepath.Join(layout.AgentsDir, "skills", repoSkillName),
		filepath.Join(layout.AgentsDir, ".skills", repoSkillName),
	)
	if layout.Mode == ModeLocal {
		report.CodexProjectRendered = isRenderedInstructionsFile(filepath.Join(layout.RootDir, "AGENTS.md"))
		report.CodexConfigShadowsGlobal = report.CodexConfigPresent
		if report.CodexConfigPresent {
			report.CodexConfigEffective = "project-local"
		}

		homeDir, err := os.UserHomeDir()
		if err != nil {
			report.CodexPrimaryConfigValid = false
			report.ClaudePrimaryConfigValid = false
			return report, fmt.Errorf("resolve home dir for project config discovery: %w", err)
		}
		homeDir, err = filepath.Abs(homeDir)
		if err != nil {
			report.CodexPrimaryConfigValid = false
			report.ClaudePrimaryConfigValid = false
			return report, fmt.Errorf("resolve home dir for project config discovery: %w", err)
		}
		globalProjectConfigPath := filepath.Join(homeDir, ".agents", ".configs", projectConfigFileName)
		gaps, gapsErr := projectPiProfileFieldGaps(ancestorDirsRootFirst(layout.RootDir), globalProjectConfigPath)
		if gapsErr != nil {
			report.CodexPrimaryConfigValid = false
			report.ClaudePrimaryConfigValid = false
			return report, gapsErr
		}
		report.PiProfileFieldGaps = gaps

		composite, err := loadCompositeProjectConfig(
			ancestorDirsRootFirst(layout.RootDir),
			globalProjectConfigPath,
		)
		if err != nil {
			report.CodexPrimaryConfigValid = false
			report.ClaudePrimaryConfigValid = false
			return report, err
		}
		if err := validateComposedCanonicalTargets(composite); err != nil {
			report.CodexPrimaryConfigValid = false
			report.ClaudePrimaryConfigValid = false
			return report, err
		}
		report.CodexMCPEnabled = composite.EnabledOrder
		report.CodexPrimarySession = composite.PrimarySession
		report.ClaudePrimarySession = composite.ClaudePrimarySession
		for _, entrypoint := range canonicalTargetLauncherNames {
			mapping, ok := composite.Entrypoints[entrypoint]
			if !ok {
				continue
			}
			target := composite.Targets[mapping.TargetName]
			item := DoctorCanonicalTarget{Entrypoint: entrypoint, EntrypointSource: mapping.Source, Name: target.Name, TargetSource: target.Source, Vendor: target.Vendor, Environment: target.Environment, Model: target.Model, Reasoning: target.Reasoning}
			if target.Profile != nil {
				item.Profile = *target.Profile
				profile := composite.PiProfiles[*target.Profile]
				item.ProfileSource = profile.Source
				item.ProfileProvider = profile.Provider
				item.Endpoint = profile.BaseURL
			}
			report.CanonicalTargets = append(report.CanonicalTargets, item)
		}
	}
	return report, nil
}

func normalizeCodexConfigMode(mode CodexConfigMode) (CodexConfigMode, error) {
	if mode == "" {
		return CodexConfigModePreserve, nil
	}
	switch mode {
	case CodexConfigModePreserve, CodexConfigModeGlobal, CodexConfigModeLocal:
		return mode, nil
	default:
		return "", fmt.Errorf("unknown Codex config mode %q (expected preserve, global, or local)", mode)
	}
}

func logf(w io.Writer, format string, args ...any) {
	if w == nil {
		return
	}
	fmt.Fprintf(w, format+"\n", args...)
}

func syncRepo(layout Layout) error {
	sourceDir := layout.SourceDir
	agentsDir := layout.AgentsDir
	if err := os.MkdirAll(agentsDir, 0o755); err != nil {
		return fmt.Errorf("create agents dir: %w", err)
	}
	return filepath.WalkDir(sourceDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(sourceDir, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		if shouldSkip(rel, d.IsDir()) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}

		dst := filepath.Join(agentsDir, rel)
		if shouldPreserveExistingLocalConfig(layout.Mode, rel, dst) {
			return nil
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		if filepath.ToSlash(rel) == managedCodexConfigRelativePath {
			return syncManagedCodexConfig(path, dst, info.Mode())
		}

		if d.Type()&os.ModeSymlink != 0 {
			target, err := os.Readlink(path)
			if err != nil {
				return fmt.Errorf("read symlink %s: %w", path, err)
			}
			return forceSymlink(target, dst)
		}

		if d.IsDir() {
			return os.MkdirAll(dst, info.Mode())
		}

		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		return copyFile(path, dst, info.Mode())
	})
}

func shouldPreserveExistingLocalConfig(mode Mode, rel, dst string) bool {
	if mode != ModeLocal || !pathExists(dst) {
		return false
	}
	switch filepath.ToSlash(rel) {
	case ".configs/claude-settings.json":
		return true
	default:
		return false
	}
}

func removeGlobalProjectConfig(layout Layout, out io.Writer) error {
	if layout.Mode != ModeGlobal {
		return nil
	}
	path := filepath.Join(layout.AgentsDir, ".configs", projectConfigFileName)
	if _, err := os.Lstat(path); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return fmt.Errorf("stat global project config %s: %w", path, err)
	}
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("remove global project config %s: %w", path, err)
	}
	logf(out, "Removed stale global project config: %s", path)
	return nil
}

func shouldSkip(rel string, isDir bool) bool {
	rel = filepath.ToSlash(rel)
	base := filepath.Base(rel)
	switch {
	case hasPathComponent(rel, ".git"):
		return true
	case rel == ".agents" || strings.HasPrefix(rel, ".agents/"):
		return true
	case rel == ".claude" || strings.HasPrefix(rel, ".claude/"):
		return true
	case rel == ".codex" || strings.HasPrefix(rel, ".codex/"):
		return true
	case rel == ".local" || strings.HasPrefix(rel, ".local/"):
		return true
	case rel == ".planning" || strings.HasPrefix(rel, ".planning/"):
		return true
	case rel == ".relux" || strings.HasPrefix(rel, ".relux/"):
		return true
	case rel == ".task-board" || strings.HasPrefix(rel, ".task-board/"):
		return true
	case rel == "skills" || strings.HasPrefix(rel, "skills/"):
		return true
	// Instruction, skill, and bundled MCP registry distribution moved to
	// Curator-managed homes. Setup neither copies these trees nor deletes
	// installed or user-managed copies; pre-existing caller files stay
	// byte-identical because sync only writes paths it walks from source.
	case rel == ".instructions" || strings.HasPrefix(rel, ".instructions/"):
		return true
	case rel == ".skills" || strings.HasPrefix(rel, ".skills/"):
		return true
	case rel == ".configs/codex-mcp-servers.toml":
		return true
	case rel == legacyLiteralSourceDirName || strings.HasPrefix(rel, legacyLiteralSourceDirName+"/"):
		return true
	case hasPathComponent(rel, ".temp"):
		return true
	// SwiftPM writes build products into `.build`. They are machine-local
	// artifacts, often hundreds of megabytes, and their bundle resources carry
	// restrictive permissions that make a copy fail outright.
	case hasPathComponent(rel, ".build"):
		return true
	// mlx-swift's Metal shaders cannot be built by SwiftPM, so that package is
	// built with `xcodebuild -derivedDataPath ./DerivedData`. The result is the
	// same class of machine-local artifact as `.build` — multiple gigabytes,
	// with bundle resources whose permissions defeat a copy.
	case hasPathComponent(rel, "DerivedData"):
		return true
	case rel == ".configs/"+projectConfigFileName:
		return true
	// A receipt is minted by a verified run, never inherited from a source tree.
	case base == runtimeReceiptFileName:
		return true
	case base == ".DS_Store", base == ".skill-lock.json", base == ".gitignore", base == ".gitattributes", base == ".gitmodules", base == "task-board.config.json":
		return true
	default:
		return false
	}
}

func scrubInstalledGitMetadata(layout Layout, out io.Writer) error {
	if samePath(layout.SourceDir, layout.AgentsDir) {
		logf(out, "Skipping git metadata cleanup because source dir equals install dir: %s", layout.AgentsDir)
		return nil
	}
	paths, err := findGitMetadataPaths(layout.AgentsDir)
	if err != nil {
		return err
	}
	for _, path := range paths {
		if err := os.RemoveAll(path); err != nil {
			return fmt.Errorf("remove %s: %w", path, err)
		}
		logf(out, "Removed installed git metadata: %s", path)
	}
	if len(paths) == 0 {
		logf(out, "Installed git metadata already absent from %s", layout.AgentsDir)
	}
	return nil
}

func findGitMetadataPaths(root string) ([]string, error) {
	var paths []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if path == root {
			return nil
		}
		base := filepath.Base(path)
		switch base {
		case ".git", ".gitignore", ".gitattributes", ".gitmodules":
			paths = append(paths, path)
			if d.IsDir() {
				return filepath.SkipDir
			}
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk git metadata in %s: %w", root, err)
	}
	sort.Strings(paths)
	return paths, nil
}

func hasPathComponent(rel, want string) bool {
	for _, part := range strings.Split(rel, "/") {
		if part == want {
			return true
		}
	}
	return false
}

func scrubGeneratedArtifacts(layout Layout, out io.Writer) error {
	roots := []string{layout.ClaudeDir, layout.CodexDir, layout.BinDir}
	if !samePath(layout.SourceDir, layout.AgentsDir) {
		roots = append([]string{layout.AgentsDir}, roots...)
	} else {
		logf(out, "Skipping generated artifact cleanup in source dir: %s", layout.AgentsDir)
	}
	for _, root := range roots {
		if err := removeGeneratedArtifacts(root, out); err != nil {
			return err
		}
	}
	return nil
}

func removeGeneratedArtifacts(root string, out io.Writer) error {
	if _, err := os.Lstat(root); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return fmt.Errorf("stat %s: %w", root, err)
	}

	var paths []string
	if err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if path == root {
			return nil
		}
		if isGeneratedArtifact(filepath.Base(path)) {
			paths = append(paths, path)
		}
		return nil
	}); err != nil {
		return fmt.Errorf("walk %s: %w", root, err)
	}

	sort.Slice(paths, func(i, j int) bool {
		return len(paths[i]) > len(paths[j])
	})
	for _, path := range paths {
		if _, err := os.Lstat(path); os.IsNotExist(err) {
			continue
		} else if err != nil {
			return fmt.Errorf("stat generated artifact %s: %w", path, err)
		}
		if err := os.RemoveAll(path); err != nil {
			return fmt.Errorf("remove generated artifact %s: %w", path, err)
		}
		logf(out, "Removed generated artifact: %s", path)
	}
	return nil
}

// setupClaudeSettings links the residual Claude settings file. Instruction
// entrypoint rendering and skill fan-out left setup with the Curator
// migration; the v1 prepare compatibility renderer still refreshes the
// instruction link and entrypoint for installed runtimes.
func setupClaudeSettings(layout Layout, out io.Writer) error {
	return createSymlink(filepath.Join(layout.AgentsDir, ".configs", "claude-settings.json"), filepath.Join(layout.ClaudeDir, "settings.json"), out)
}

// setupCodex refreshes the residual Codex surface: the caller-selected config
// state plus rules links. Instruction entrypoint rendering and skill fan-out
// left setup with the Curator migration.
func setupCodex(layout Layout, codexConfigMode CodexConfigMode, out io.Writer) error {
	if err := setupCodexProjectConfig(layout, codexConfigMode, out); err != nil {
		return err
	}
	return setupCodexRules(layout, out)
}

// setupCodexProjectConfig applies the caller-selected Codex config state.
// Global setup links the managed config; local setup honors the explicit
// preserve/global/local mode.
func setupCodexProjectConfig(layout Layout, codexConfigMode CodexConfigMode, out io.Writer) error {
	codexConfigPath := filepath.Join(layout.CodexDir, "config.toml")
	agentsCodexConfigPath := filepath.Join(layout.AgentsDir, ".configs", "codex-config.toml")
	if layout.Mode == ModeGlobal {
		return createSymlink(agentsCodexConfigPath, codexConfigPath, out)
	}
	mode, err := normalizeCodexConfigMode(codexConfigMode)
	if err != nil {
		return err
	}
	switch mode {
	case CodexConfigModePreserve:
		if err := removeGeneratedProjectCodexConfig(codexConfigPath, out); err != nil {
			return err
		}
		localConfigPresent, err := removeLegacyProjectCodexConfig(codexConfigPath, agentsCodexConfigPath, out)
		if err != nil {
			return err
		}
		if localConfigPresent {
			logf(out, "Project-local Codex config remains in place and overrides global Codex config")
		} else {
			logf(out, "Skipped project-local Codex config so global config remains authoritative")
		}
	case CodexConfigModeGlobal:
		if err := removeManagedPath(codexConfigPath, out); err != nil {
			return err
		}
		logf(out, "Ensured no project-local Codex config so global config remains authoritative")
	case CodexConfigModeLocal:
		if err := renderProjectCodexConfig(agentsCodexConfigPath, codexConfigPath, out); err != nil {
			return err
		}
	}
	return nil
}

// setupCodexRules links the residual Codex rules tree.
func setupCodexRules(layout Layout, out io.Writer) error {
	if err := os.MkdirAll(filepath.Join(layout.CodexDir, "rules"), 0o755); err != nil {
		return err
	}
	rulesDir := filepath.Join(layout.AgentsDir, ".rules")
	rules, err := os.ReadDir(rulesDir)
	if err != nil {
		return err
	}
	for _, entry := range rules {
		if entry.IsDir() || shouldIgnoreGeneratedEntry(entry.Name()) {
			continue
		}
		if err := createSymlink(filepath.Join(rulesDir, entry.Name()), filepath.Join(layout.CodexDir, "rules", entry.Name()), out); err != nil {
			return err
		}
	}
	return nil
}

type codexMCPServer struct {
	URL               string
	BearerTokenEnvVar string
	Command           string
	Args              []string
}

func projectEnabledMCPServers(layout Layout) ([]string, error) {
	path := filepath.Join(layout.AgentsDir, ".configs", projectConfigFileName)
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read project config %s: %w", path, err)
	}
	return parseEnabledMCPServers(data, path, "mcp")
}

func parseEnabledMCPServers(data []byte, path, wantSection string) ([]string, error) {
	if wantSection != "mcp" {
		return nil, fmt.Errorf("unsupported project config MCP section %q", wantSection)
	}
	config, err := parseProjectConfig(data, path)
	if err != nil {
		return nil, err
	}
	return config.EnabledMCPServers, nil
}

func removeGeneratedProjectCodexConfig(path string, out io.Writer) error {
	if !isGeneratedCodexConfigFile(path) {
		return nil
	}
	if err := os.Remove(path); err != nil {
		return err
	}
	logf(out, "Removed generated project-local Codex config: %s", path)
	return nil
}

// parseCodexMCPRegistry and the codexMCPServer shape below are the retained
// registry-read contract for compose: caller-supplied global and project
// registries keep working, and a configured server without a definition keeps
// failing closed. Setup no longer ships a bundled registry.
func parseCodexMCPRegistry(data []byte, path string) (map[string]codexMCPServer, error) {
	servers := map[string]codexMCPServer{}
	var current string
	for lineNo, rawLine := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(line, "["), "]"))
			if strings.HasPrefix(section, "servers.") {
				current = strings.TrimPrefix(section, "servers.")
				if current == "" {
					return nil, fmt.Errorf("%s:%d: empty MCP server name", path, lineNo+1)
				}
				if !isBareTOMLKey(current) {
					return nil, fmt.Errorf("%s:%d: unsupported MCP server name %q", path, lineNo+1, current)
				}
				if _, ok := servers[current]; !ok {
					servers[current] = codexMCPServer{}
				}
			} else {
				current = ""
			}
			continue
		}
		if current == "" {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			return nil, fmt.Errorf("%s:%d: expected key = value", path, lineNo+1)
		}
		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)
		server := servers[current]
		switch key {
		case "url":
			parsed, err := parseTOMLString(value)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: parse %s: %w", path, lineNo+1, key, err)
			}
			server.URL = parsed
		case "bearer_token_env_var":
			parsed, err := parseTOMLString(value)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: parse %s: %w", path, lineNo+1, key, err)
			}
			server.BearerTokenEnvVar = parsed
		case "command":
			parsed, err := parseTOMLString(value)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: parse %s: %w", path, lineNo+1, key, err)
			}
			server.Command = parsed
		case "args":
			parsed, err := parseTOMLStringArray(value)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: parse %s: %w", path, lineNo+1, key, err)
			}
			server.Args = parsed
		}
		servers[current] = server
	}
	return servers, nil
}

func parseTOMLStringArray(value string) ([]string, error) {
	if !strings.HasPrefix(value, "[") || !strings.HasSuffix(value, "]") {
		return nil, fmt.Errorf("expected string array")
	}
	inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(value, "["), "]"))
	if inner == "" {
		return nil, nil
	}
	parts := strings.Split(inner, ",")
	values := make([]string, 0, len(parts))
	for _, part := range parts {
		parsed, err := parseTOMLString(strings.TrimSpace(part))
		if err != nil {
			return nil, err
		}
		values = append(values, parsed)
	}
	return values, nil
}

func parseTOMLString(value string) (string, error) {
	parsed, err := strconv.Unquote(value)
	if err != nil {
		return "", err
	}
	return parsed, nil
}

func isBareTOMLKey(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range value {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' || r == '-' {
			continue
		}
		return false
	}
	return true
}

func removeLegacyProjectCodexConfig(path, legacyTarget string, out io.Writer) (bool, error) {
	target, err := os.Readlink(path)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err == nil {
		if symlinkTargetMatches(target, legacyTarget, filepath.Dir(path)) {
			if removeErr := os.Remove(path); removeErr != nil {
				return false, removeErr
			}
			logf(out, "Removed legacy project-local Codex config: %s", path)
		} else {
			logf(out, "Left project-local Codex config in place: %s -> %s", path, target)
			return true, nil
		}
		return false, nil
	}
	if !pathExists(path) {
		return false, err
	}
	logf(out, "Left project-local Codex config in place: %s", path)
	return true, nil
}

func setupHelpers(layout Layout, out io.Writer) error {
	if err := os.MkdirAll(layout.BinDir, 0o755); err != nil {
		return err
	}
	if err := removeLegacyAgentsAttachmentsScript(layout, out); err != nil {
		return err
	}
	if err := installAgentsAttachmentsLauncher(layout, out); err != nil {
		return err
	}
	if err := installPiInfraLauncher(layout, out); err != nil {
		return err
	}
	if err := installCanonicalTargetLaunchers(layout, out); err != nil {
		return err
	}
	if err := installDirectProviderYoloLaunchers(layout, out); err != nil {
		return err
	}
	if err := setupCodexLocalLauncher(layout, out); err != nil {
		return err
	}
	return nil
}

var canonicalTargetLauncherNames = []string{"openai-infra", "anthropic-infra", "qwen-infra"}

type directProviderYoloLauncher struct {
	name            string
	canonicalTarget string
}

var directProviderYoloLaunchers = []directProviderYoloLauncher{
	{name: "openai-dange", canonicalTarget: "openai-infra"},
	{name: "anthropic-dange", canonicalTarget: "anthropic-infra"},
}

func installCanonicalTargetLaunchers(layout Layout, out io.Writer) error {
	for _, entrypoint := range canonicalTargetLauncherNames {
		path := filepath.Join(layout.BinDir, canonicalTargetWrapperName(entrypoint, runtime.GOOS))
		body := canonicalTargetWrapperBody(entrypoint, runtime.GOOS, piInfraTargetName(layout.Mode, runtime.GOOS))
		if info, err := os.Lstat(path); err == nil && info.Mode().IsRegular() {
			modeMatches := runtime.GOOS == "windows" || info.Mode().Perm() == 0o755
			if existing, readErr := os.ReadFile(path); readErr == nil && string(existing) == body && modeMatches {
				logf(out, "Canonical target launcher already up to date: %s", path)
				continue
			}
		}
		if err := removeManagedPath(path, out); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
			return fmt.Errorf("write canonical target launcher %s: %w", entrypoint, err)
		}
		logf(out, "Installed canonical target launcher: %s", path)
	}
	return nil
}

func canonicalTargetWrapperName(entrypoint, goos string) string {
	if strings.EqualFold(goos, "windows") {
		return entrypoint + ".cmd"
	}
	return entrypoint
}

func canonicalTargetWrapperBody(entrypoint, goos, targetName string) string {
	// Deprecated aliases refuse directly in the wrapper, before any sibling
	// lookup, build, or exec. Delegating to the local agents-infra launcher
	// would rebuild the Go binary (a filesystem write) before the Go
	// dispatcher could refuse, and a failing toolchain would mask the
	// migration notice with a build error.
	if message, ok := DeprecatedProviderMessage(entrypoint); ok {
		if strings.EqualFold(goos, "windows") {
			return cmdDeprecationRefusalBody(message)
		}
		return posixDeprecationRefusalBody(message)
	}
	if strings.EqualFold(goos, "windows") {
		return fmt.Sprintf("@echo off\r\nsetlocal\r\nset \"DIR=%%~dp0\"\r\nif not exist \"%%DIR%%%s\" (\r\n  echo %s: missing or non-regular sibling %%DIR%%%s 1^>^&2\r\n  exit /b 127\r\n)\r\n\"%%DIR%%%s\" target %s %%*\r\nexit /b %%ERRORLEVEL%%\r\n", targetName, entrypoint, targetName, targetName, entrypoint)
	}
	return fmt.Sprintf(`#!/usr/bin/env sh
set -eu
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
TARGET="$DIR/%s"
if [ ! -f "$TARGET" ] || [ -L "$TARGET" ] || [ ! -x "$TARGET" ]; then
  echo "%s: missing or non-regular sibling $TARGET" >&2
  exit 127
fi
exec "$TARGET" target %s "$@"
`, targetName, entrypoint, entrypoint)
}

func installDirectProviderYoloLaunchers(layout Layout, out io.Writer) error {
	for _, launcher := range directProviderYoloLaunchers {
		path := filepath.Join(layout.BinDir, canonicalTargetWrapperName(launcher.name, runtime.GOOS))
		body := directProviderYoloWrapperBody(launcher, runtime.GOOS, piInfraTargetName(layout.Mode, runtime.GOOS))
		if info, err := os.Lstat(path); err == nil && info.Mode().IsRegular() {
			modeMatches := runtime.GOOS == "windows" || info.Mode().Perm() == 0o755
			if existing, readErr := os.ReadFile(path); readErr == nil && string(existing) == body && modeMatches {
				logf(out, "Direct provider YOLO launcher already up to date: %s", path)
				continue
			}
		}
		if err := removeManagedPath(path, out); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
			return fmt.Errorf("write direct provider YOLO launcher %s: %w", launcher.name, err)
		}
		logf(out, "Installed direct provider YOLO launcher: %s", path)
	}
	return nil
}

func directProviderYoloWrapperBody(launcher directProviderYoloLauncher, goos, targetName string) string {
	// Both shipped dange aliases are deprecated and refuse directly, for the
	// same build-before-refusal reason as the canonical aliases. The
	// delegation branch below remains for a future live alias only.
	if message, ok := DeprecatedProviderMessage(launcher.name); ok {
		if strings.EqualFold(goos, "windows") {
			return cmdDeprecationRefusalBody(message)
		}
		return posixDeprecationRefusalBody(message)
	}
	if strings.EqualFold(goos, "windows") {
		return fmt.Sprintf("@echo off\r\nsetlocal\r\nset \"DIR=%%~dp0\"\r\nif not exist \"%%DIR%%%s\" (\r\n  echo %s: missing sibling target %%DIR%%%s 1^>^&2\r\n  exit /b 127\r\n)\r\n\"%%DIR%%%s\" target-yolo %s %%*\r\nexit /b %%ERRORLEVEL%%\r\n", targetName, launcher.name, targetName, targetName, launcher.canonicalTarget)
	}
	return fmt.Sprintf(`#!/usr/bin/env sh
set -eu
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
TARGET="$DIR/%s"
if [ ! -f "$TARGET" ] || [ -L "$TARGET" ] || [ ! -x "$TARGET" ]; then
  echo "%s: missing or non-regular sibling $TARGET" >&2
  exit 127
fi
exec "$TARGET" target-yolo %s "$@"
`, targetName, launcher.name, launcher.canonicalTarget)
}

func installPiInfraLauncher(layout Layout, out io.Writer) error {
	path := filepath.Join(layout.BinDir, piInfraWrapperName(runtime.GOOS))
	body := piInfraWrapperBody(runtime.GOOS, piInfraTargetName(layout.Mode, runtime.GOOS))
	if info, err := os.Lstat(path); err == nil && info.Mode().IsRegular() {
		modeMatches := runtime.GOOS == "windows" || info.Mode().Perm() == 0o755
		if existing, readErr := os.ReadFile(path); readErr == nil && string(existing) == body && modeMatches {
			logf(out, "Pi launcher already up to date: %s", path)
			return nil
		}
	}
	if err := removeManagedPath(path, out); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return fmt.Errorf("write Pi launcher: %w", err)
	}
	logf(out, "Installed Pi launcher: %s", path)
	return nil
}

func piInfraWrapperName(goos string) string {
	if strings.EqualFold(goos, "windows") {
		return "pi-infra.cmd"
	}
	return "pi-infra"
}

func piInfraTargetName(mode Mode, goos string) string {
	if strings.EqualFold(goos, "windows") {
		if mode == ModeGlobal {
			return "agents-infra.exe"
		}
		return "agents-infra.cmd"
	}
	return "agents-infra"
}

func piInfraWrapperBody(goos, targetName string) string {
	if strings.EqualFold(goos, "windows") {
		return fmt.Sprintf("@echo off\r\nsetlocal\r\nset \"DIR=%%~dp0\"\r\nif not exist \"%%DIR%%%s\" (\r\n  echo pi-infra: missing managed target %%DIR%%%s 1^>^&2\r\n  exit /b 127\r\n)\r\n\"%%DIR%%%s\" pi %%*\r\nexit /b %%ERRORLEVEL%%\r\n", targetName, targetName, targetName)
	}
	return fmt.Sprintf(`#!/usr/bin/env sh
set -eu
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
TARGET="$DIR/%s"
if [ ! -x "$TARGET" ]; then
  echo "pi-infra: missing managed target $TARGET" >&2
  exit 127
fi
exec "$TARGET" pi "$@"
`, targetName)
}

func removeLegacyAgentsAttachmentsScript(layout Layout, out io.Writer) error {
	path := filepath.Join(layout.AgentsDir, ".scripts", "agents-attachments")
	if _, err := os.Lstat(path); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return err
	}
	if err := removeManagedPath(path, out); err != nil {
		return err
	}
	logf(out, "Removed legacy Python agents-attachments helper: %s", path)
	return nil
}

func installAgentsAttachmentsLauncher(layout Layout, out io.Writer) error {
	path := filepath.Join(layout.BinDir, agentsAttachmentsWrapperName(runtime.GOOS))
	body := agentsAttachmentsWrapperBody(runtime.GOOS)
	if existing, err := os.ReadFile(path); err == nil && string(existing) == body {
		logf(out, "Agents attachments launcher already up to date: %s", path)
		return nil
	}
	if err := removeManagedPath(path, out); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return fmt.Errorf("write agents attachments launcher: %w", err)
	}
	logf(out, "Installed agents attachments launcher: %s", path)
	return nil
}

func agentsAttachmentsWrapperName(goos string) string {
	if strings.EqualFold(goos, "windows") {
		return "agents-attachments.cmd"
	}
	return "agents-attachments"
}

func agentsAttachmentsWrapperBody(goos string) string {
	if strings.EqualFold(goos, "windows") {
		return "@echo off\r\nsetlocal\r\nset \"DIR=%~dp0\"\r\nif exist \"%DIR%agents-infra.cmd\" (\r\n  \"%DIR%agents-infra.cmd\" attachments %*\r\n  exit /b\r\n)\r\nif exist \"%DIR%agents-infra.exe\" (\r\n  \"%DIR%agents-infra.exe\" attachments %*\r\n  exit /b\r\n)\r\nagents-infra attachments %*\r\nexit /b\r\n"
	}
	return `#!/usr/bin/env sh
set -eu
DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
if [ -x "$DIR/agents-infra" ]; then
  TARGET="$DIR/agents-infra"
else
  TARGET=agents-infra
fi
STATUS_FILE=$(mktemp "${TMPDIR:-/tmp}/agents-attachments.XXXXXX")
trap 'rm -f "$STATUS_FILE"' EXIT HUP INT TERM
if "$TARGET" attachments "$@" 2>"$STATUS_FILE"; then
  STATUS=0
else
  STATUS=$?
fi
MAPPED_STATUS=$(sed -n '$s/^exit status \([0-9][0-9]*\)$/\1/p' "$STATUS_FILE")
if [ -n "$MAPPED_STATUS" ]; then
  sed '$d' "$STATUS_FILE" >&2
  exit "$MAPPED_STATUS"
fi
cat "$STATUS_FILE" >&2
exit "$STATUS"
`
}

func isGeneratedAgentsAttachmentsLauncher(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	body := string(data)
	return strings.Contains(body, "agents-infra") && strings.Contains(body, "attachments")
}

func setupCodexLocalLauncher(layout Layout, out io.Writer) error {
	if layout.Mode != ModeLocal {
		return nil
	}
	path := filepath.Join(layout.BinDir, "codex-local")
	enabledServers, err := projectEnabledMCPServers(layout)
	if err != nil {
		return err
	}
	if len(enabledServers) == 0 {
		return removeGeneratedCodexLocalLauncher(path, out)
	}
	body := codexLocalLauncherBody()
	if existing, err := os.ReadFile(path); err == nil && string(existing) == body {
		logf(out, "Codex local MCP launcher already up to date: %s", path)
		return nil
	}
	if err := removeManagedPath(path, out); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return fmt.Errorf("write Codex local MCP launcher: %w", err)
	}
	logf(out, "Installed Codex local MCP launcher: %s", path)
	return nil
}

func codexLocalLauncherBody() string {
	// The shim keeps its generated marker (the opt-out lifecycle keys on it)
	// but refuses directly with the CLI codex message. Forwarding to
	// `agents-infra codex` would rebuild the Go binary before the Go
	// dispatcher could refuse.
	message, _ := DeprecatedProviderMessage("codex")
	var body strings.Builder
	body.WriteString("#!/usr/bin/env sh\n")
	body.WriteString(generatedCodexConfigMarker)
	body.WriteString("\n")
	body.WriteString("set -eu\n")
	body.WriteString("printf '%s\\n' " + posixShellQuote(message) + " >&2\n")
	body.WriteString("exit 1\n")
	return body.String()
}

func removeGeneratedCodexLocalLauncher(path string, out io.Writer) error {
	if !isGeneratedCodexLocalLauncher(path) {
		return nil
	}
	if err := os.Remove(path); err != nil {
		return err
	}
	logf(out, "Removed generated Codex local MCP launcher: %s", path)
	return nil
}

func installCLIWrapper(layout Layout, out io.Writer) error {
	if layout.Mode == ModeGlobal {
		logf(out, "Skipping local CLI wrapper install for global setup; bootstrap owns ~/.local/bin/agents-infra")
		return nil
	}
	if err := os.MkdirAll(layout.BinDir, 0o755); err != nil {
		return err
	}
	goos := runtime.GOOS
	path := filepath.Join(layout.BinDir, cliWrapperName(goos))
	sourceDir := layout.SourceDir
	if sourceDir == "" {
		sourceDir = layout.AgentsDir
	}
	body := cliWrapperBody(goos, sourceDir, cliLocalBinaryPath(layout, goos))
	if existing, err := os.ReadFile(path); err == nil && string(existing) == body {
		logf(out, "CLI launcher already up to date: %s", path)
		return nil
	}
	if err := removeManagedPath(path, out); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return fmt.Errorf("write cli wrapper: %w", err)
	}
	logf(out, "Installed CLI launcher: %s", path)
	return nil
}

func cliWrapperName(goos string) string {
	if strings.EqualFold(goos, "windows") {
		return "agents-infra.cmd"
	}
	return "agents-infra"
}

// cliLocalBinaryDirName holds the binary the generated launcher builds and then
// executes. It lives inside the target's own bin dir — the tree this setup run
// was asked to write — and deliberately not in the shared source checkout.
//
// Writing the build output into the source made three things impossible to
// state truthfully. A launcher installed for one project raced every other
// project's launcher over one path; a source checkout that is read-only, or
// whose scratch dir is not writable, produced a launcher that installed and
// verified and then failed on first use; and verification could not reproduce
// the real output path without mutating the tree it was checking. Keeping the
// output in the target removes all three: the path setup attests is the path
// the launcher uses.
const cliLocalBinaryDirName = ".agents-infra-build"

func cliLocalBinaryName(goos string) string {
	if strings.EqualFold(goos, "windows") {
		return "agents-infra-local.exe"
	}
	return "agents-infra-local"
}

// cliLocalBinaryPath is the single definition of where the generated launcher
// writes its build output; the wrapper bakes it in and verification reads it
// back out of the wrapper, so the two cannot drift apart.
func cliLocalBinaryPath(layout Layout, goos string) string {
	return filepath.Join(layout.BinDir, cliLocalBinaryDirName, cliLocalBinaryName(goos))
}

func cliWrapperBody(goos, sourceDir, binaryPath string) string {
	// The deprecation guard runs before the wrapper creates its build
	// directory or invokes the Go toolchain, so `agents-infra codex`,
	// `agents-infra target openai-infra`, and the other retired subcommands
	// refuse without a filesystem write even when the cached build output is
	// absent or the toolchain is broken.
	if strings.EqualFold(goos, "windows") {
		return fmt.Sprintf("@echo off\r\nsetlocal\r\n%s"+
			"set \"AGENTS_INFRA_SOURCE_DIR=%s\"\r\nset \"AGENTS_INFRA_CALLER_CWD=%%CD%%\"\r\nset \"AGENTS_INFRA_BINARY=%s\"\r\nif not exist \"%s\" mkdir \"%s\"\r\ncd /d \"%%AGENTS_INFRA_SOURCE_DIR%%\\tools\\agents-infra\"\r\ngo build -o \"%%AGENTS_INFRA_BINARY%%\" .\r\nif errorlevel 1 exit /b %%ERRORLEVEL%%\r\n\"%%AGENTS_INFRA_BINARY%%\" %%*\r\nexit /b %%ERRORLEVEL%%\r\n",
			cmdCLIWrapperDeprecationGuard(), sourceDir, binaryPath, filepath.Dir(binaryPath), filepath.Dir(binaryPath))
	}
	return fmt.Sprintf(`#!/usr/bin/env sh
set -eu
%s`+
		`export AGENTS_INFRA_SOURCE_DIR=%q
AGENTS_INFRA_CALLER_CWD=$(pwd)
export AGENTS_INFRA_CALLER_CWD
AGENTS_INFRA_BINARY=%q
mkdir -p "$(dirname -- "$AGENTS_INFRA_BINARY")"
cd "$AGENTS_INFRA_SOURCE_DIR/tools/agents-infra"
go build -o "$AGENTS_INFRA_BINARY" .
exec "$AGENTS_INFRA_BINARY" "$@"
`, posixCLIWrapperDeprecationGuard(), sourceDir, binaryPath)
}

// The v1 instruction renderer (writeClaudeEntrypoint, writeCodexEntrypoints,
// and the include helpers) moved to legacy_prepare_instructions.go with the
// Curator migration; only PreparePrimarySession calls it.

func createSymlink(target, link string, out io.Writer) error {
	if err := os.MkdirAll(filepath.Dir(link), 0o755); err != nil {
		return err
	}
	if existingTarget, err := os.Readlink(link); err == nil {
		if existingTarget == target {
			return nil
		}
		if err := os.Remove(link); err != nil {
			return err
		}
		logf(out, "Removed existing symlink: %s", link)
	} else if !os.IsNotExist(err) {
		if err := removeManagedPath(link, out); err != nil {
			return err
		}
	}
	if err := os.Symlink(target, link); err != nil {
		return fmt.Errorf("create symlink %s -> %s: %w", link, target, err)
	}
	logf(out, "Created symlink: %s -> %s", link, target)
	return nil
}

func removeManagedPath(path string, out io.Writer) error {
	st, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return err
	}
	if st.IsDir() && st.Mode()&os.ModeSymlink == 0 {
		if err := os.RemoveAll(path); err != nil {
			return err
		}
		logf(out, "Removed existing directory: %s", path)
		return nil
	}
	if err := os.Remove(path); err != nil {
		return err
	}
	logf(out, "Removed existing managed path: %s", path)
	return nil
}

func forceSymlink(target, path string) error {
	if existingTarget, err := os.Readlink(path); err == nil {
		if existingTarget == target {
			return nil
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		if err := os.RemoveAll(path); err != nil {
			return err
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.Symlink(target, path)
}

func copyFile(src, dst string, mode fs.FileMode) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	if st, err := os.Lstat(dst); err == nil {
		if st.IsDir() {
			if err := os.RemoveAll(dst); err != nil {
				return err
			}
		} else if st.Mode()&os.ModeSymlink != 0 {
			if err := os.Remove(dst); err != nil {
				return err
			}
		}
	}
	out, err := os.OpenFile(dst, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, mode)
	if err != nil {
		return err
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

func samePath(a, b string) bool {
	aa, errA := filepath.Abs(a)
	bb, errB := filepath.Abs(b)
	if errA != nil || errB != nil {
		return samePathName(a, b)
	}
	aa = filepath.Clean(aa)
	bb = filepath.Clean(bb)
	if samePathName(aa, bb) {
		return true
	}

	anchorA, suffixA, okA := existingPathIdentity(aa)
	anchorB, suffixB, okB := existingPathIdentity(bb)
	if !okA || !okB || len(suffixA) != len(suffixB) || !os.SameFile(anchorA, anchorB) {
		return false
	}
	for index := range suffixA {
		if !samePathName(suffixA[index], suffixB[index]) {
			return false
		}
	}
	return true
}

func samePathName(a, b string) bool {
	if runtime.GOOS == "windows" {
		return strings.EqualFold(a, b)
	}
	return a == b
}

// existingPathIdentity returns the nearest existing ancestor and the missing
// path components below it. Comparing both pieces recognizes symlink and other
// filesystem aliases even when the final project-config file does not exist.
func existingPathIdentity(path string) (fs.FileInfo, []string, bool) {
	current := path
	var suffix []string
	for {
		info, err := os.Stat(current)
		if err == nil {
			return info, suffix, true
		}
		if !os.IsNotExist(err) {
			return nil, nil, false
		}
		parent := filepath.Dir(current)
		if parent == current {
			return nil, nil, false
		}
		suffix = append([]string{filepath.Base(current)}, suffix...)
		current = parent
	}
}

func isLinkTo(path, target string) bool {
	got, err := os.Readlink(path)
	if err != nil {
		return false
	}
	return symlinkTargetMatches(got, target, filepath.Dir(path))
}

func symlinkTargetMatches(got, target, linkDir string) bool {
	if !filepath.IsAbs(got) {
		got = filepath.Join(linkDir, got)
	}
	return samePath(got, target)
}

func pathExists(path string) bool {
	_, err := os.Lstat(path)
	return err == nil
}

func isRenderedInstructionsFile(path string) bool {
	st, err := os.Lstat(path)
	if err != nil || st.Mode()&os.ModeSymlink != 0 {
		return false
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	body := string(data)
	return strings.Contains(body, generatedInstructionsMarker) && !containsInstructionInclude(body)
}

func isGeneratedCodexConfigFile(path string) bool {
	st, err := os.Lstat(path)
	if err != nil || st.Mode()&os.ModeSymlink != 0 {
		return false
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), generatedCodexConfigMarker)
}

func isGeneratedCodexLocalLauncher(path string) bool {
	st, err := os.Lstat(path)
	if err != nil || st.Mode()&os.ModeSymlink != 0 {
		return false
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), generatedCodexConfigMarker)
}

func containsInstructionInclude(body string) bool {
	for _, line := range strings.Split(body, "\n") {
		if _, ok := parseInstructionInclude(line); ok {
			return true
		}
	}
	return false
}

func shouldIgnoreGeneratedEntry(name string) bool {
	return strings.HasPrefix(name, ".") || strings.Contains(name, ".bak.")
}

func isGeneratedArtifact(name string) bool {
	return name == ".DS_Store" || name == ".temp" || name == ".task-board" || name == "task-board.config.json" || name == legacyLiteralSourceDirName || strings.Contains(name, ".bak.")
}
