package infra

import (
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strconv"
	"strings"
)

type Mode string

const (
	ModeGlobal Mode = "global"
	ModeLocal  Mode = "local"
)

type CodexConfigMode string

const (
	CodexConfigModePreserve CodexConfigMode = "preserve"
	CodexConfigModeGlobal   CodexConfigMode = "global"
	CodexConfigModeLocal    CodexConfigMode = "local"
)

type Layout struct {
	Mode      Mode
	SourceDir string
	RootDir   string
	AgentsDir string
	ClaudeDir string
	CodexDir  string
	BinDir    string
}

type Options struct {
	Layout                    Layout
	NoSync                    bool
	CodexConfigMode           CodexConfigMode
	PrimarySessionSetup       CodexPrimarySessionSetup
	ClaudePrimarySessionSetup ClaudePrimarySessionSetup
	Stdout                    io.Writer
	projectConfigAtomicWriter projectConfigAtomicWriter
}

type Report struct {
	Layout                   Layout
	AgentsGitFree            bool
	ClaudeLinked             bool
	CodexLinked              bool
	CodexRendered            bool
	CodexProjectRendered     bool
	CodexConfigPresent       bool
	CodexConfigLinked        bool
	CodexConfigGenerated     bool
	CodexConfigShadowsGlobal bool
	CodexConfigEffective     string
	CodexMCPEnabled          []string
	CodexPrimaryConfigValid  bool
	CodexPrimarySession      CodexPrimarySessionPolicy
	ClaudePrimaryConfigValid bool
	ClaudePrimarySession     ClaudePrimarySessionPolicy
	HelpersLinked            bool
	InfraSkillLink           bool
}

const generatedInstructionsMarker = "<!-- Generated by agents-infra; do not edit directly. -->"
const generatedCodexConfigMarker = "# Generated by agents-infra; do not edit directly."
const projectConfigFileName = "project-config.toml"
const repoSkillName = "relux-agents-infra"

func GlobalLayout(sourceDir, homeDir string) (Layout, error) {
	if homeDir == "" {
		return Layout{}, fmt.Errorf("home directory is required")
	}
	homeDir, err := filepath.Abs(homeDir)
	if err != nil {
		return Layout{}, fmt.Errorf("resolve home dir: %w", err)
	}
	return Layout{
		Mode:      ModeGlobal,
		SourceDir: sourceDir,
		RootDir:   homeDir,
		AgentsDir: filepath.Join(homeDir, ".agents"),
		ClaudeDir: filepath.Join(homeDir, ".claude"),
		CodexDir:  filepath.Join(homeDir, ".codex"),
		BinDir:    filepath.Join(homeDir, ".local", "bin"),
	}, nil
}

func LocalLayout(sourceDir, projectDir string) (Layout, error) {
	if projectDir == "" {
		return Layout{}, fmt.Errorf("project directory is required")
	}
	projectDir, err := filepath.Abs(projectDir)
	if err != nil {
		return Layout{}, fmt.Errorf("resolve project dir: %w", err)
	}
	return Layout{
		Mode:      ModeLocal,
		SourceDir: sourceDir,
		RootDir:   projectDir,
		AgentsDir: filepath.Join(projectDir, ".agents"),
		ClaudeDir: filepath.Join(projectDir, ".claude"),
		CodexDir:  filepath.Join(projectDir, ".codex"),
		BinDir:    filepath.Join(projectDir, ".local", "bin"),
	}, nil
}

func Setup(opts Options) error {
	if _, err := normalizeCodexConfigMode(opts.CodexConfigMode); err != nil {
		return err
	}
	preparedProjectConfig, err := preparePrimarySessionSetup(
		opts.Layout,
		opts.PrimarySessionSetup,
		opts.ClaudePrimarySessionSetup,
		opts.projectConfigAtomicWriter,
	)
	if err != nil {
		return err
	}
	if opts.Layout.SourceDir == "" {
		return fmt.Errorf("source dir is required")
	}
	if !opts.NoSync {
		if err := syncRepo(opts.Layout); err != nil {
			return err
		}
		logf(opts.Stdout, "Synced source repo into %s", opts.Layout.AgentsDir)
	}
	if err := removeGlobalProjectConfig(opts.Layout, opts.Stdout); err != nil {
		return err
	}
	if err := scrubInstalledGitMetadata(opts.Layout, opts.Stdout); err != nil {
		return err
	}
	if err := scrubGeneratedArtifacts(opts.Layout, opts.Stdout); err != nil {
		return err
	}
	if err := RefreshLinks(opts); err != nil {
		return err
	}
	return commitPreparedProjectConfig(preparedProjectConfig, opts.Stdout)
}

func RefreshLinks(opts Options) error {
	if _, err := normalizeCodexConfigMode(opts.CodexConfigMode); err != nil {
		return err
	}
	if err := ensureRepoSkillLinks(opts.Layout, opts.Stdout); err != nil {
		return err
	}
	if err := setupClaude(opts.Layout, opts.Stdout); err != nil {
		return err
	}
	if err := setupCodex(opts.Layout, opts.CodexConfigMode, opts.Stdout); err != nil {
		return err
	}
	if err := setupHelpers(opts.Layout, opts.Stdout); err != nil {
		return err
	}
	return installCLIWrapper(opts.Layout, opts.Stdout)
}

func Doctor(layout Layout) (Report, error) {
	report := Report{
		Layout:                   layout,
		CodexPrimaryConfigValid:  true,
		ClaudePrimaryConfigValid: true,
	}
	if _, err := os.Stat(filepath.Join(layout.AgentsDir, ".git")); err == nil {
		report.AgentsGitFree = false
	} else {
		report.AgentsGitFree = true
	}
	report.ClaudeLinked = isLinkTo(filepath.Join(layout.ClaudeDir, "instructions"), filepath.Join(layout.AgentsDir, ".instructions"))
	report.CodexLinked = isLinkTo(filepath.Join(layout.CodexDir, "AGENTS.md"), filepath.Join(layout.AgentsDir, ".instructions", "AGENTS.md"))
	report.CodexRendered = isRenderedInstructionsFile(filepath.Join(layout.CodexDir, "AGENTS.md"))
	codexConfigPath := filepath.Join(layout.CodexDir, "config.toml")
	report.CodexConfigPresent = pathExists(codexConfigPath)
	report.CodexConfigLinked = isLinkTo(codexConfigPath, filepath.Join(layout.AgentsDir, ".configs", "codex-config.toml"))
	report.CodexConfigGenerated = isGeneratedCodexConfigFile(codexConfigPath)
	report.CodexConfigEffective = "global"
	report.HelpersLinked = isLinkTo(filepath.Join(layout.BinDir, "agents-attachments"), filepath.Join(layout.AgentsDir, ".scripts", "agents-attachments"))
	report.InfraSkillLink = isLinkTo(filepath.Join(layout.AgentsDir, "skills", repoSkillName), layout.AgentsDir)
	if layout.Mode == ModeLocal {
		report.CodexProjectRendered = isRenderedInstructionsFile(filepath.Join(layout.RootDir, "AGENTS.md"))
		report.CodexConfigShadowsGlobal = report.CodexConfigPresent
		if report.CodexConfigPresent {
			report.CodexConfigEffective = "project-local"
		}

		homeDir, err := os.UserHomeDir()
		if err != nil {
			report.CodexPrimaryConfigValid = false
			report.ClaudePrimaryConfigValid = false
			return report, fmt.Errorf("resolve home dir for project config discovery: %w", err)
		}
		homeDir, err = filepath.Abs(homeDir)
		if err != nil {
			report.CodexPrimaryConfigValid = false
			report.ClaudePrimaryConfigValid = false
			return report, fmt.Errorf("resolve home dir for project config discovery: %w", err)
		}
		composite, err := loadCompositeProjectConfig(
			ancestorDirsRootFirst(layout.RootDir),
			filepath.Join(homeDir, ".agents", ".configs", projectConfigFileName),
		)
		if err != nil {
			report.CodexPrimaryConfigValid = false
			report.ClaudePrimaryConfigValid = false
			return report, err
		}
		report.CodexMCPEnabled = composite.EnabledOrder
		report.CodexPrimarySession = composite.PrimarySession
		report.ClaudePrimarySession = composite.ClaudePrimarySession
	}
	return report, nil
}

func normalizeCodexConfigMode(mode CodexConfigMode) (CodexConfigMode, error) {
	if mode == "" {
		return CodexConfigModePreserve, nil
	}
	switch mode {
	case CodexConfigModePreserve, CodexConfigModeGlobal, CodexConfigModeLocal:
		return mode, nil
	default:
		return "", fmt.Errorf("unknown Codex config mode %q (expected preserve, global, or local)", mode)
	}
}

func logf(w io.Writer, format string, args ...any) {
	if w == nil {
		return
	}
	fmt.Fprintf(w, format+"\n", args...)
}

func syncRepo(layout Layout) error {
	sourceDir := layout.SourceDir
	agentsDir := layout.AgentsDir
	if err := os.MkdirAll(agentsDir, 0o755); err != nil {
		return fmt.Errorf("create agents dir: %w", err)
	}
	return filepath.WalkDir(sourceDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(sourceDir, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		if shouldSkip(rel, d.IsDir()) {
			if d.IsDir() {
				return filepath.SkipDir
			}
			return nil
		}

		dst := filepath.Join(agentsDir, rel)
		if shouldPreserveExistingLocalConfig(layout.Mode, rel, dst) {
			return nil
		}
		info, err := d.Info()
		if err != nil {
			return err
		}

		if d.Type()&os.ModeSymlink != 0 {
			target, err := os.Readlink(path)
			if err != nil {
				return fmt.Errorf("read symlink %s: %w", path, err)
			}
			return forceSymlink(target, dst)
		}

		if d.IsDir() {
			return os.MkdirAll(dst, info.Mode())
		}

		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		return copyFile(path, dst, info.Mode())
	})
}

func shouldPreserveExistingLocalConfig(mode Mode, rel, dst string) bool {
	if mode != ModeLocal || !pathExists(dst) {
		return false
	}
	switch filepath.ToSlash(rel) {
	case ".configs/codex-config.toml", ".configs/claude-settings.json":
		return true
	default:
		return false
	}
}

func removeGlobalProjectConfig(layout Layout, out io.Writer) error {
	if layout.Mode != ModeGlobal {
		return nil
	}
	path := filepath.Join(layout.AgentsDir, ".configs", projectConfigFileName)
	if _, err := os.Lstat(path); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return fmt.Errorf("stat global project config %s: %w", path, err)
	}
	if err := os.Remove(path); err != nil {
		return fmt.Errorf("remove global project config %s: %w", path, err)
	}
	logf(out, "Removed stale global project config: %s", path)
	return nil
}

func shouldSkip(rel string, isDir bool) bool {
	rel = filepath.ToSlash(rel)
	base := filepath.Base(rel)
	switch {
	case hasPathComponent(rel, ".git"):
		return true
	case rel == ".agents" || strings.HasPrefix(rel, ".agents/"):
		return true
	case rel == ".claude" || strings.HasPrefix(rel, ".claude/"):
		return true
	case rel == ".codex" || strings.HasPrefix(rel, ".codex/"):
		return true
	case rel == ".local" || strings.HasPrefix(rel, ".local/"):
		return true
	case rel == ".planning" || strings.HasPrefix(rel, ".planning/"):
		return true
	case rel == ".relux" || strings.HasPrefix(rel, ".relux/"):
		return true
	case rel == ".task-board" || strings.HasPrefix(rel, ".task-board/"):
		return true
	case rel == "skills" || strings.HasPrefix(rel, "skills/"):
		return true
	case rel == ".temp" || strings.HasPrefix(rel, ".temp/"):
		return true
	case rel == ".configs/"+projectConfigFileName:
		return true
	case base == ".DS_Store", base == ".skill-lock.json", base == ".gitignore", base == ".gitattributes", base == ".gitmodules", base == "task-board.config.json":
		return true
	default:
		return false
	}
}

func scrubInstalledGitMetadata(layout Layout, out io.Writer) error {
	if samePath(layout.SourceDir, layout.AgentsDir) {
		logf(out, "Skipping git metadata cleanup because source dir equals install dir: %s", layout.AgentsDir)
		return nil
	}
	paths, err := findGitMetadataPaths(layout.AgentsDir)
	if err != nil {
		return err
	}
	for _, path := range paths {
		if err := os.RemoveAll(path); err != nil {
			return fmt.Errorf("remove %s: %w", path, err)
		}
		logf(out, "Removed installed git metadata: %s", path)
	}
	if len(paths) == 0 {
		logf(out, "Installed git metadata already absent from %s", layout.AgentsDir)
	}
	return nil
}

func findGitMetadataPaths(root string) ([]string, error) {
	var paths []string
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if path == root {
			return nil
		}
		base := filepath.Base(path)
		switch base {
		case ".git", ".gitignore", ".gitattributes", ".gitmodules":
			paths = append(paths, path)
			if d.IsDir() {
				return filepath.SkipDir
			}
		}
		return nil
	})
	if err != nil {
		return nil, fmt.Errorf("walk git metadata in %s: %w", root, err)
	}
	sort.Strings(paths)
	return paths, nil
}

func hasPathComponent(rel, want string) bool {
	for _, part := range strings.Split(rel, "/") {
		if part == want {
			return true
		}
	}
	return false
}

func scrubGeneratedArtifacts(layout Layout, out io.Writer) error {
	roots := []string{layout.ClaudeDir, layout.CodexDir, layout.BinDir}
	if !samePath(layout.SourceDir, layout.AgentsDir) {
		roots = append([]string{layout.AgentsDir}, roots...)
	} else {
		logf(out, "Skipping generated artifact cleanup in source dir: %s", layout.AgentsDir)
	}
	for _, root := range roots {
		if err := removeGeneratedArtifacts(root, out); err != nil {
			return err
		}
	}
	return nil
}

func removeGeneratedArtifacts(root string, out io.Writer) error {
	if _, err := os.Lstat(root); os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return fmt.Errorf("stat %s: %w", root, err)
	}

	var paths []string
	if err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if path == root {
			return nil
		}
		if isGeneratedArtifact(filepath.Base(path)) {
			paths = append(paths, path)
		}
		return nil
	}); err != nil {
		return fmt.Errorf("walk %s: %w", root, err)
	}

	sort.Slice(paths, func(i, j int) bool {
		return len(paths[i]) > len(paths[j])
	})
	for _, path := range paths {
		if _, err := os.Lstat(path); os.IsNotExist(err) {
			continue
		} else if err != nil {
			return fmt.Errorf("stat generated artifact %s: %w", path, err)
		}
		if err := os.RemoveAll(path); err != nil {
			return fmt.Errorf("remove generated artifact %s: %w", path, err)
		}
		logf(out, "Removed generated artifact: %s", path)
	}
	return nil
}

func ensureRepoSkillLinks(layout Layout, out io.Writer) error {
	skillsDir := filepath.Join(layout.AgentsDir, "skills")
	if err := os.MkdirAll(skillsDir, 0o755); err != nil {
		return fmt.Errorf("create skills dir: %w", err)
	}
	if err := createSymlink(layout.AgentsDir, filepath.Join(skillsDir, repoSkillName), out); err != nil {
		return err
	}
	if err := removeStaleRepoSkillLinks(skillsDir, layout.AgentsDir, out); err != nil {
		return err
	}
	hiddenSkillsDir := filepath.Join(layout.AgentsDir, ".skills")
	entries, err := os.ReadDir(hiddenSkillsDir)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("read hidden skills dir: %w", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() || shouldIgnoreGeneratedEntry(entry.Name()) {
			continue
		}
		target := filepath.Join(hiddenSkillsDir, entry.Name())
		link := filepath.Join(skillsDir, entry.Name())
		if err := createSymlink(target, link, out); err != nil {
			return err
		}
	}
	return nil
}

func removeStaleRepoSkillLinks(skillsDir, agentsDir string, out io.Writer) error {
	entries, err := os.ReadDir(skillsDir)
	if err != nil {
		return fmt.Errorf("read skills dir: %w", err)
	}
	for _, entry := range entries {
		if entry.Name() == repoSkillName {
			continue
		}
		path := filepath.Join(skillsDir, entry.Name())
		info, err := os.Lstat(path)
		if err != nil {
			return fmt.Errorf("stat skill link %s: %w", path, err)
		}
		if info.Mode()&os.ModeSymlink == 0 {
			continue
		}
		if !isLinkTo(path, agentsDir) {
			continue
		}
		if err := os.Remove(path); err != nil {
			if os.IsPermission(err) {
				logf(out, "Skipped stale repo skill link removal after permission error: %s", path)
				continue
			}
			return fmt.Errorf("remove stale repo skill link %s: %w", path, err)
		}
		logf(out, "Removed stale repo skill link: %s", path)
	}
	return nil
}

func removeDanglingManagedSkillLinks(skillsDir, managedSkillsDir string, out io.Writer) error {
	entries, err := os.ReadDir(skillsDir)
	if err != nil {
		return fmt.Errorf("read skills dir: %w", err)
	}
	managedSkillsDir, err = filepath.Abs(managedSkillsDir)
	if err != nil {
		return fmt.Errorf("resolve managed skills dir: %w", err)
	}
	for _, entry := range entries {
		path := filepath.Join(skillsDir, entry.Name())
		info, err := os.Lstat(path)
		if err != nil {
			return fmt.Errorf("stat skill link %s: %w", path, err)
		}
		if info.Mode()&os.ModeSymlink == 0 {
			continue
		}
		target, err := os.Readlink(path)
		if err != nil {
			return fmt.Errorf("read skill link %s: %w", path, err)
		}
		if !filepath.IsAbs(target) {
			target = filepath.Join(skillsDir, target)
		}
		target, err = filepath.Abs(target)
		if err != nil {
			return fmt.Errorf("resolve skill link target %s: %w", path, err)
		}
		if target != managedSkillsDir && !strings.HasPrefix(target, managedSkillsDir+string(os.PathSeparator)) {
			continue
		}
		if _, err := os.Lstat(target); err == nil {
			continue
		} else if !os.IsNotExist(err) {
			return fmt.Errorf("stat managed skill target %s: %w", target, err)
		}
		if err := os.Remove(path); err != nil {
			return fmt.Errorf("remove dangling managed skill link %s: %w", path, err)
		}
		logf(out, "Removed dangling managed skill link: %s", path)
	}
	return nil
}

func setupClaude(layout Layout, out io.Writer) error {
	claudeSkillsDir := filepath.Join(layout.ClaudeDir, "skills")
	if err := os.MkdirAll(claudeSkillsDir, 0o755); err != nil {
		return err
	}
	if err := createSymlink(filepath.Join(layout.AgentsDir, ".instructions"), filepath.Join(layout.ClaudeDir, "instructions"), out); err != nil {
		return err
	}
	if err := writeClaudeEntrypoint(layout); err != nil {
		return err
	}
	skillsDir := filepath.Join(layout.AgentsDir, "skills")
	if err := removeDanglingManagedSkillLinks(claudeSkillsDir, skillsDir, out); err != nil {
		return err
	}
	entries, err := os.ReadDir(skillsDir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		sourcePath := filepath.Join(skillsDir, entry.Name())
		if shouldSkipSkillFanout(entry.Name(), sourcePath, layout.AgentsDir, out) {
			continue
		}
		if err := createSymlink(sourcePath, filepath.Join(claudeSkillsDir, entry.Name()), out); err != nil {
			return err
		}
	}
	return createSymlink(filepath.Join(layout.AgentsDir, ".configs", "claude-settings.json"), filepath.Join(layout.ClaudeDir, "settings.json"), out)
}

func setupCodex(layout Layout, codexConfigMode CodexConfigMode, out io.Writer) error {
	codexSkillsDir := filepath.Join(layout.CodexDir, "skills")
	if err := os.MkdirAll(codexSkillsDir, 0o755); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(layout.CodexDir, "rules"), 0o755); err != nil {
		return err
	}
	if err := writeCodexEntrypoints(layout, out); err != nil {
		return err
	}
	skillsDir := filepath.Join(layout.AgentsDir, "skills")
	if err := removeDanglingManagedSkillLinks(codexSkillsDir, skillsDir, out); err != nil {
		return err
	}
	entries, err := os.ReadDir(skillsDir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		sourcePath := filepath.Join(skillsDir, entry.Name())
		if shouldSkipSkillFanout(entry.Name(), sourcePath, layout.AgentsDir, out) {
			continue
		}
		systemSkill := filepath.Join(layout.CodexDir, "skills", ".system", entry.Name())
		if st, err := os.Stat(systemSkill); err == nil && st.IsDir() {
			logf(out, "Skipping %s because it exists in %s", entry.Name(), systemSkill)
			continue
		}
		if err := createSymlink(sourcePath, filepath.Join(codexSkillsDir, entry.Name()), out); err != nil {
			return err
		}
	}
	codexConfigPath := filepath.Join(layout.CodexDir, "config.toml")
	agentsCodexConfigPath := filepath.Join(layout.AgentsDir, ".configs", "codex-config.toml")
	if layout.Mode == ModeGlobal {
		if err := createSymlink(agentsCodexConfigPath, codexConfigPath, out); err != nil {
			return err
		}
	} else {
		mode, err := normalizeCodexConfigMode(codexConfigMode)
		if err != nil {
			return err
		}
		switch mode {
		case CodexConfigModePreserve:
			if err := removeGeneratedProjectCodexConfig(codexConfigPath, out); err != nil {
				return err
			}
			localConfigPresent, err := removeLegacyProjectCodexConfig(codexConfigPath, agentsCodexConfigPath, out)
			if err != nil {
				return err
			}
			if localConfigPresent {
				logf(out, "Project-local Codex config remains in place and overrides global Codex config")
			} else {
				logf(out, "Skipped project-local Codex config so global config remains authoritative")
			}
		case CodexConfigModeGlobal:
			if err := removeManagedPath(codexConfigPath, out); err != nil {
				return err
			}
			logf(out, "Ensured no project-local Codex config so global config remains authoritative")
		case CodexConfigModeLocal:
			if err := createSymlink(agentsCodexConfigPath, codexConfigPath, out); err != nil {
				return err
			}
			logf(out, "Linked project-local Codex config: %s", codexConfigPath)
		}
	}
	rulesDir := filepath.Join(layout.AgentsDir, ".rules")
	rules, err := os.ReadDir(rulesDir)
	if err != nil {
		return err
	}
	for _, entry := range rules {
		if entry.IsDir() || shouldIgnoreGeneratedEntry(entry.Name()) {
			continue
		}
		if err := createSymlink(filepath.Join(rulesDir, entry.Name()), filepath.Join(layout.CodexDir, "rules", entry.Name()), out); err != nil {
			return err
		}
	}
	return nil
}

func shouldSkipSkillFanout(name, path, agentsDir string, out io.Writer) bool {
	if shouldIgnoreGeneratedEntry(name) {
		return true
	}
	if name == repoSkillName || !isLinkTo(path, agentsDir) {
		return false
	}
	logf(out, "Skipping stale repo skill link during fan-out: %s", path)
	return true
}

type codexMCPServer struct {
	URL               string
	BearerTokenEnvVar string
	Command           string
	Args              []string
}

func projectEnabledMCPServers(layout Layout) ([]string, error) {
	path := filepath.Join(layout.AgentsDir, ".configs", projectConfigFileName)
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read project config %s: %w", path, err)
	}
	return parseEnabledMCPServers(data, path, "mcp")
}

func parseEnabledMCPServers(data []byte, path, wantSection string) ([]string, error) {
	if wantSection != "mcp" {
		return nil, fmt.Errorf("unsupported project config MCP section %q", wantSection)
	}
	config, err := parseProjectConfig(data, path)
	if err != nil {
		return nil, err
	}
	return config.EnabledMCPServers, nil
}

func removeGeneratedProjectCodexConfig(path string, out io.Writer) error {
	if !isGeneratedCodexConfigFile(path) {
		return nil
	}
	if err := os.Remove(path); err != nil {
		return err
	}
	logf(out, "Removed generated project-local Codex config: %s", path)
	return nil
}

func loadCodexMCPRegistry(layout Layout) (map[string]codexMCPServer, error) {
	path := filepath.Join(layout.AgentsDir, ".configs", "codex-mcp-servers.toml")
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read Codex MCP registry %s: %w", path, err)
	}
	return parseCodexMCPRegistry(data, path)
}

func parseCodexMCPRegistry(data []byte, path string) (map[string]codexMCPServer, error) {
	servers := map[string]codexMCPServer{}
	var current string
	for lineNo, rawLine := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(rawLine)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
			section := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(line, "["), "]"))
			if strings.HasPrefix(section, "servers.") {
				current = strings.TrimPrefix(section, "servers.")
				if current == "" {
					return nil, fmt.Errorf("%s:%d: empty MCP server name", path, lineNo+1)
				}
				if !isBareTOMLKey(current) {
					return nil, fmt.Errorf("%s:%d: unsupported MCP server name %q", path, lineNo+1, current)
				}
				if _, ok := servers[current]; !ok {
					servers[current] = codexMCPServer{}
				}
			} else {
				current = ""
			}
			continue
		}
		if current == "" {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			return nil, fmt.Errorf("%s:%d: expected key = value", path, lineNo+1)
		}
		key = strings.TrimSpace(key)
		value = strings.TrimSpace(value)
		server := servers[current]
		switch key {
		case "url":
			parsed, err := parseTOMLString(value)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: parse %s: %w", path, lineNo+1, key, err)
			}
			server.URL = parsed
		case "bearer_token_env_var":
			parsed, err := parseTOMLString(value)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: parse %s: %w", path, lineNo+1, key, err)
			}
			server.BearerTokenEnvVar = parsed
		case "command":
			parsed, err := parseTOMLString(value)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: parse %s: %w", path, lineNo+1, key, err)
			}
			server.Command = parsed
		case "args":
			parsed, err := parseTOMLStringArray(value)
			if err != nil {
				return nil, fmt.Errorf("%s:%d: parse %s: %w", path, lineNo+1, key, err)
			}
			server.Args = parsed
		}
		servers[current] = server
	}
	return servers, nil
}

func parseTOMLStringArray(value string) ([]string, error) {
	if !strings.HasPrefix(value, "[") || !strings.HasSuffix(value, "]") {
		return nil, fmt.Errorf("expected string array")
	}
	inner := strings.TrimSpace(strings.TrimSuffix(strings.TrimPrefix(value, "["), "]"))
	if inner == "" {
		return nil, nil
	}
	parts := strings.Split(inner, ",")
	values := make([]string, 0, len(parts))
	for _, part := range parts {
		parsed, err := parseTOMLString(strings.TrimSpace(part))
		if err != nil {
			return nil, err
		}
		values = append(values, parsed)
	}
	return values, nil
}

func parseTOMLString(value string) (string, error) {
	parsed, err := strconv.Unquote(value)
	if err != nil {
		return "", err
	}
	return parsed, nil
}

func isBareTOMLKey(value string) bool {
	if value == "" {
		return false
	}
	for _, r := range value {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '_' || r == '-' {
			continue
		}
		return false
	}
	return true
}

func removeLegacyProjectCodexConfig(path, legacyTarget string, out io.Writer) (bool, error) {
	target, err := os.Readlink(path)
	if os.IsNotExist(err) {
		return false, nil
	}
	if err == nil {
		if symlinkTargetMatches(target, legacyTarget, filepath.Dir(path)) {
			if removeErr := os.Remove(path); removeErr != nil {
				return false, removeErr
			}
			logf(out, "Removed legacy project-local Codex config: %s", path)
		} else {
			logf(out, "Left project-local Codex config in place: %s -> %s", path, target)
			return true, nil
		}
		return false, nil
	}
	if !pathExists(path) {
		return false, err
	}
	logf(out, "Left project-local Codex config in place: %s", path)
	return true, nil
}

func setupHelpers(layout Layout, out io.Writer) error {
	if err := os.MkdirAll(layout.BinDir, 0o755); err != nil {
		return err
	}
	if err := createSymlink(filepath.Join(layout.AgentsDir, ".scripts", "agents-attachments"), filepath.Join(layout.BinDir, "agents-attachments"), out); err != nil {
		return err
	}
	if err := setupCodexLocalLauncher(layout, out); err != nil {
		return err
	}
	return nil
}

func setupCodexLocalLauncher(layout Layout, out io.Writer) error {
	if layout.Mode != ModeLocal {
		return nil
	}
	path := filepath.Join(layout.BinDir, "codex-local")
	enabledServers, err := projectEnabledMCPServers(layout)
	if err != nil {
		return err
	}
	if len(enabledServers) == 0 {
		return removeGeneratedCodexLocalLauncher(path, out)
	}
	body := codexLocalLauncherBody()
	if existing, err := os.ReadFile(path); err == nil && string(existing) == body {
		logf(out, "Codex local MCP launcher already up to date: %s", path)
		return nil
	}
	if err := removeManagedPath(path, out); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return fmt.Errorf("write Codex local MCP launcher: %w", err)
	}
	logf(out, "Installed Codex local MCP launcher: %s", path)
	return nil
}

func codexLocalLauncherBody() string {
	var body strings.Builder
	body.WriteString("#!/usr/bin/env sh\n")
	body.WriteString(generatedCodexConfigMarker)
	body.WriteString("\n")
	body.WriteString("set -eu\n")
	body.WriteString("DIR=$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\n")
	body.WriteString("if [ -x \"$DIR/agents-infra\" ]; then\n")
	body.WriteString("  exec \"$DIR/agents-infra\" codex \"$@\"\n")
	body.WriteString("fi\n")
	body.WriteString("exec agents-infra codex \"$@\"\n")
	return body.String()
}

func removeGeneratedCodexLocalLauncher(path string, out io.Writer) error {
	if !isGeneratedCodexLocalLauncher(path) {
		return nil
	}
	if err := os.Remove(path); err != nil {
		return err
	}
	logf(out, "Removed generated Codex local MCP launcher: %s", path)
	return nil
}

func installCLIWrapper(layout Layout, out io.Writer) error {
	if layout.Mode == ModeGlobal {
		logf(out, "Skipping local CLI wrapper install for global setup; bootstrap owns ~/.local/bin/agents-infra")
		return nil
	}
	if err := os.MkdirAll(layout.BinDir, 0o755); err != nil {
		return err
	}
	goos := runtime.GOOS
	path := filepath.Join(layout.BinDir, cliWrapperName(goos))
	sourceDir := layout.SourceDir
	if sourceDir == "" {
		sourceDir = layout.AgentsDir
	}
	body := cliWrapperBody(goos, sourceDir)
	if existing, err := os.ReadFile(path); err == nil && string(existing) == body {
		logf(out, "CLI launcher already up to date: %s", path)
		return nil
	}
	if err := removeManagedPath(path, out); err != nil {
		return err
	}
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return fmt.Errorf("write cli wrapper: %w", err)
	}
	logf(out, "Installed CLI launcher: %s", path)
	return nil
}

func cliWrapperName(goos string) string {
	if strings.EqualFold(goos, "windows") {
		return "agents-infra.cmd"
	}
	return "agents-infra"
}

func cliWrapperBody(goos, sourceDir string) string {
	if strings.EqualFold(goos, "windows") {
		return fmt.Sprintf("@echo off\r\nsetlocal\r\nset \"AGENTS_INFRA_SOURCE_DIR=%s\"\r\nset \"AGENTS_INFRA_CALLER_CWD=%%CD%%\"\r\ncd /d \"%%AGENTS_INFRA_SOURCE_DIR%%\\tools\\agents-infra\"\r\ngo run . %%*\r\n", sourceDir)
	}
	return fmt.Sprintf(`#!/usr/bin/env sh
set -eu
export AGENTS_INFRA_SOURCE_DIR=%q
AGENTS_INFRA_CALLER_CWD=$(pwd)
export AGENTS_INFRA_CALLER_CWD
cd "$AGENTS_INFRA_SOURCE_DIR/tools/agents-infra"
exec go run . "$@"
`, sourceDir)
}

func writeClaudeEntrypoint(layout Layout) error {
	body := "# Claude Instructions\n\nLoad all instructions from the Claude runtime instructions directory:\n\n@instructions/INSTRUCTIONS.md\n"
	return os.WriteFile(filepath.Join(layout.ClaudeDir, "CLAUDE.md"), []byte(body), 0o644)
}

type renderSource struct {
	path           string
	includeBaseDir string
}

func writeCodexEntrypoints(layout Layout, out io.Writer) error {
	source := defaultInstructionSource(layout)
	if layout.Mode == ModeLocal {
		projectSource, err := projectInstructionSource(layout, out)
		if err != nil {
			return err
		}
		source = projectSource
	}
	if err := writeRenderedInstructions(filepath.Join(layout.CodexDir, "AGENTS.md"), source, layout, out); err != nil {
		return err
	}
	if layout.Mode != ModeLocal {
		return nil
	}
	return writeRenderedInstructions(filepath.Join(layout.RootDir, "AGENTS.md"), source, layout, out)
}

func defaultInstructionSource(layout Layout) renderSource {
	path := filepath.Join(layout.AgentsDir, ".instructions", "AGENTS.md")
	return renderSource{path: path, includeBaseDir: filepath.Dir(path)}
}

func projectInstructionSource(layout Layout, out io.Writer) (renderSource, error) {
	preserved := filepath.Join(layout.AgentsDir, ".instructions", "AGENTS.project.md")
	if _, err := os.Stat(preserved); err == nil {
		return renderSource{path: preserved, includeBaseDir: layout.RootDir}, nil
	} else if !os.IsNotExist(err) {
		return renderSource{}, err
	}

	projectDoc := filepath.Join(layout.RootDir, "AGENTS.md")
	data, err := os.ReadFile(projectDoc)
	if os.IsNotExist(err) {
		return defaultInstructionSource(layout), nil
	}
	if err != nil {
		return renderSource{}, fmt.Errorf("read project AGENTS.md: %w", err)
	}
	if strings.Contains(string(data), generatedInstructionsMarker) {
		return defaultInstructionSource(layout), nil
	}
	if err := os.MkdirAll(filepath.Dir(preserved), 0o755); err != nil {
		return renderSource{}, err
	}
	if err := os.WriteFile(preserved, data, 0o644); err != nil {
		return renderSource{}, fmt.Errorf("preserve project AGENTS.md source: %w", err)
	}
	logf(out, "Preserved project AGENTS.md source: %s", preserved)
	return renderSource{path: preserved, includeBaseDir: layout.RootDir}, nil
}

func writeRenderedInstructions(target string, source renderSource, layout Layout, out io.Writer) error {
	rendered, err := renderInstructions(source, layout, map[string]bool{})
	if err != nil {
		return err
	}
	body := generatedInstructionsMarker + "\n" +
		fmt.Sprintf("<!-- Source: %s -->\n\n", filepath.ToSlash(source.path)) +
		rendered
	if !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	if err := removeManagedPath(target, out); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(target, []byte(body), 0o644); err != nil {
		return fmt.Errorf("write rendered instructions %s: %w", target, err)
	}
	logf(out, "Rendered Codex instructions: %s", target)
	return nil
}

func renderInstructions(source renderSource, layout Layout, stack map[string]bool) (string, error) {
	abs, err := filepath.Abs(source.path)
	if err != nil {
		return "", err
	}
	if stack[abs] {
		return "", fmt.Errorf("cyclic instruction include: %s", source.path)
	}
	data, err := os.ReadFile(source.path)
	if err != nil {
		return "", fmt.Errorf("read instruction file %s: %w", source.path, err)
	}

	stack[abs] = true
	defer delete(stack, abs)

	var out strings.Builder
	lines := strings.SplitAfter(string(data), "\n")
	for _, line := range lines {
		includeRef, ok := parseInstructionInclude(line)
		if !ok {
			out.WriteString(line)
			continue
		}
		includePath, err := resolveInstructionInclude(includeRef, source.includeBaseDir, layout)
		if err != nil {
			return "", err
		}
		rendered, err := renderInstructions(renderSource{path: includePath, includeBaseDir: filepath.Dir(includePath)}, layout, stack)
		if err != nil {
			return "", err
		}
		out.WriteString(rendered)
		if !strings.HasSuffix(rendered, "\n") {
			out.WriteString("\n")
		}
	}
	return out.String(), nil
}

func parseInstructionInclude(line string) (string, bool) {
	trimmed := strings.TrimSpace(line)
	if !strings.HasPrefix(trimmed, "@") {
		return "", false
	}
	ref := strings.TrimSpace(strings.TrimPrefix(trimmed, "@"))
	if ref == "" || strings.ContainsAny(ref, " \t") {
		return "", false
	}
	if !strings.HasSuffix(strings.ToLower(ref), ".md") {
		return "", false
	}
	return ref, true
}

func resolveInstructionInclude(ref, baseDir string, layout Layout) (string, error) {
	const agentsHomePrefix = "~/.agents/"
	if strings.HasPrefix(ref, agentsHomePrefix) {
		return filepath.Join(layout.AgentsDir, filepath.FromSlash(strings.TrimPrefix(ref, agentsHomePrefix))), nil
	}
	if strings.HasPrefix(ref, "~/") {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", fmt.Errorf("resolve home dir for include %s: %w", ref, err)
		}
		return filepath.Join(home, filepath.FromSlash(strings.TrimPrefix(ref, "~/"))), nil
	}
	if filepath.IsAbs(ref) {
		return ref, nil
	}
	return filepath.Join(baseDir, filepath.FromSlash(ref)), nil
}

func createSymlink(target, link string, out io.Writer) error {
	if err := os.MkdirAll(filepath.Dir(link), 0o755); err != nil {
		return err
	}
	if existingTarget, err := os.Readlink(link); err == nil {
		if existingTarget == target {
			return nil
		}
		if err := os.Remove(link); err != nil {
			return err
		}
		logf(out, "Removed existing symlink: %s", link)
	} else if !os.IsNotExist(err) {
		if err := removeManagedPath(link, out); err != nil {
			return err
		}
	}
	if err := os.Symlink(target, link); err != nil {
		return fmt.Errorf("create symlink %s -> %s: %w", link, target, err)
	}
	logf(out, "Created symlink: %s -> %s", link, target)
	return nil
}

func removeManagedPath(path string, out io.Writer) error {
	st, err := os.Lstat(path)
	if os.IsNotExist(err) {
		return nil
	} else if err != nil {
		return err
	}
	if st.IsDir() && st.Mode()&os.ModeSymlink == 0 {
		if err := os.RemoveAll(path); err != nil {
			return err
		}
		logf(out, "Removed existing directory: %s", path)
		return nil
	}
	if err := os.Remove(path); err != nil {
		return err
	}
	logf(out, "Removed existing managed path: %s", path)
	return nil
}

func forceSymlink(target, path string) error {
	if existingTarget, err := os.Readlink(path); err == nil {
		if existingTarget == target {
			return nil
		}
		if err := os.Remove(path); err != nil {
			return err
		}
	} else if !os.IsNotExist(err) {
		if err := os.RemoveAll(path); err != nil {
			return err
		}
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.Symlink(target, path)
}

func copyFile(src, dst string, mode fs.FileMode) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	if st, err := os.Lstat(dst); err == nil {
		if st.IsDir() {
			if err := os.RemoveAll(dst); err != nil {
				return err
			}
		} else if st.Mode()&os.ModeSymlink != 0 {
			if err := os.Remove(dst); err != nil {
				return err
			}
		}
	}
	out, err := os.OpenFile(dst, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, mode)
	if err != nil {
		return err
	}
	defer out.Close()
	if _, err := io.Copy(out, in); err != nil {
		return err
	}
	return out.Close()
}

func samePath(a, b string) bool {
	aa, errA := filepath.Abs(a)
	bb, errB := filepath.Abs(b)
	if errA != nil || errB != nil {
		return samePathName(a, b)
	}
	aa = filepath.Clean(aa)
	bb = filepath.Clean(bb)
	if samePathName(aa, bb) {
		return true
	}

	anchorA, suffixA, okA := existingPathIdentity(aa)
	anchorB, suffixB, okB := existingPathIdentity(bb)
	if !okA || !okB || len(suffixA) != len(suffixB) || !os.SameFile(anchorA, anchorB) {
		return false
	}
	for index := range suffixA {
		if !samePathName(suffixA[index], suffixB[index]) {
			return false
		}
	}
	return true
}

func samePathName(a, b string) bool {
	if runtime.GOOS == "windows" {
		return strings.EqualFold(a, b)
	}
	return a == b
}

// existingPathIdentity returns the nearest existing ancestor and the missing
// path components below it. Comparing both pieces recognizes symlink and other
// filesystem aliases even when the final project-config file does not exist.
func existingPathIdentity(path string) (fs.FileInfo, []string, bool) {
	current := path
	var suffix []string
	for {
		info, err := os.Stat(current)
		if err == nil {
			return info, suffix, true
		}
		if !os.IsNotExist(err) {
			return nil, nil, false
		}
		parent := filepath.Dir(current)
		if parent == current {
			return nil, nil, false
		}
		suffix = append([]string{filepath.Base(current)}, suffix...)
		current = parent
	}
}

func isLinkTo(path, target string) bool {
	got, err := os.Readlink(path)
	if err != nil {
		return false
	}
	return symlinkTargetMatches(got, target, filepath.Dir(path))
}

func symlinkTargetMatches(got, target, linkDir string) bool {
	if !filepath.IsAbs(got) {
		got = filepath.Join(linkDir, got)
	}
	return samePath(got, target)
}

func pathExists(path string) bool {
	_, err := os.Lstat(path)
	return err == nil
}

func isRenderedInstructionsFile(path string) bool {
	st, err := os.Lstat(path)
	if err != nil || st.Mode()&os.ModeSymlink != 0 {
		return false
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	body := string(data)
	return strings.Contains(body, generatedInstructionsMarker) && !containsInstructionInclude(body)
}

func isGeneratedCodexConfigFile(path string) bool {
	st, err := os.Lstat(path)
	if err != nil || st.Mode()&os.ModeSymlink != 0 {
		return false
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), generatedCodexConfigMarker)
}

func isGeneratedCodexLocalLauncher(path string) bool {
	st, err := os.Lstat(path)
	if err != nil || st.Mode()&os.ModeSymlink != 0 {
		return false
	}
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), generatedCodexConfigMarker)
}

func containsInstructionInclude(body string) bool {
	for _, line := range strings.Split(body, "\n") {
		if _, ok := parseInstructionInclude(line); ok {
			return true
		}
	}
	return false
}

func shouldIgnoreGeneratedEntry(name string) bool {
	return strings.HasPrefix(name, ".") || strings.Contains(name, ".bak.")
}

func isGeneratedArtifact(name string) bool {
	return name == ".DS_Store" || name == ".task-board" || name == "task-board.config.json" || strings.Contains(name, ".bak.")
}
